version: '3'

services:

  mtproxy:
    image: alexdoesh/mtproxy
    container_name: mtproxy
    restart: always
    # command: --add --your --commands
    # environment:
    #   - OVERRIDE=SOME
    #   - VARIABLES=HERE
    volumes:
      - ./config:/data
    ports:
      - "$PORT:$PORT"
    networks:
      - tg_stack

networks:
  tg_stack:

